{{- if .Values.podDisruptionBudget.backend.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "fynncloud.fullname" . }}-backend
  labels:
    {{- include "fynncloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  {{- if .Values.podDisruptionBudget.backend.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.backend.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.backend.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.backend.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fynncloud.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
{{- end }}
