{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "fynncloud.gateway.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fynncloud.labels" . | nindent 4 }}
    {{- with .Values.gateway.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  {{- with .Values.gateway.listeners }}
  listeners:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.gateway.addresses }}
  addresses:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
